changeLogFile=./changelog/master_szk_qa.xml
url=jdbc:oracle:thin:@192.168.160.5:1521/SZK_QC?oracle.jdbc.timezoneAsRegion=false

username=JD_BAHAMONDE[ADMSCB]
password=1234

driver=oracle.jdbc.OracleDriver
